---
title: 'New Year, New Post'
author: Grace Acton
date: '2023-01-05' 
slug: new-project
categories:
  - research
tags:
  - Bates
  - Rufus Porter
publishdate: '2022-11-10T15:32:54-05:00'
comments: yes
---

## Long time no see! 

Friends, it's been a very busy semester and holiday season. But, I want to share some updates before the winter semester starts next week!   

### New Digital Exhibit

I took two wonderful history classes this semester. Taking Technology in US History was an absolute highlight for me; the course started out solidly in my 18th and 19th century comfort zone, covering railroads, mills, and agriculture, but by the second half we were talking about modern technology that I regularly use but hadn't thought about critically. It really gave me a new lens on "digital history" -- this time meaning the history of digital tools, rather than using those tools for historical work.

My other history class was called _Upstairs, Downstairs, and Outside: The Household in British History_ and was also right up my alley! I never had a chance to take a European history class in high school, so I was very fortunate to find a British history survey course that was based in a topic that I'm very comfortable with.

For my final project in the British history class, I created a digital exhibit on food policy during the World Wars. I had so much fun looking through museum collections for posters, recipes, advertisements, photos, and other artifacts. Check it out [here](https://inds281.omeka.net/exhibits/show/exhibit)!

### Ongoing Internship at the Bates Museum

I was very fortunate to have a spot in the Bates Art Museum internship course last semester, and I'm so happy to say that I'll be continuing my work next semester! The museum has asked me to develop a crowdsourcing platform to allow volunteers to help update the tags and descriptions of objects in our publicly-available [collections database](https://museum.bates.edu/). I've been having a blast playing around with the ArtUK [Tagger](https://artuk.org/participate/tagger) interface, and similar projects built with [Zooniverse](https://www.zooniverse.org/projects). We ultimately decided to use Zooniverse for our own platform, and I'm looking forward to fine-tuning our questions and user interface!

### Next Semester's Classes

This winter semester I'm taking three academic courses and ballet, which gives me more time to work on my museum project. For academics, I'm taking my final Advanced Russian course, a history class on celebrations and daily life in Medieval Europe, and a data-science-slash-history class called Archives, Data, and Analysis. This is the last DCS/History class I have left, meaning I'm basically done with my major, other than completing my thesis! 

I'll likely be blogging much more next semester - I have a lot of digital history work coming up that I'd really like to share! Beyond the Zooniverse museum project and my DCS/History class, I'm also working on expanding my Rufus Porter [project](https://www.rufusportermuseum.org/interactive-map) using data from Zillow. I think this will be a really fun and engaging semester academically, and I look forward to sharing my progress with all of you! 
